### ISSUE TITLE
Reworking the ring mechanic

### ISSUE THREAD

**Issue by Helliaca** [Helliaca/HoI4-LotrMod#43]

**Comment by RubenVermaat** [comment]
#44 test

**Comment by Helliaca** [comment]
Potentially useful: https://www.reddit.com/r/lotr/comments/1870r9/map_of_characters_paths_through_the_books_my/

**Comment by Helliaca** [comment]
Some thinkable paths: 
![image](https://user-images.githubusercontent.com/18307020/211795049-61b4942a-ebe8-414b-8f04-1e9e5ff7ddd3.png)

**Comment by Helliaca** [comment]
Members:
	Frodo
	Sam
	Gandalf / Gollum
	Aragorn / Arwen
	Boromir / Faramir
	Legolas / Tauriel
	Gimli / Gloin
	Merrin
	Pippin








variables:
	- fs_map
	- fs_strength
	- fs_currentstate
	- fs_members_[membername]
	- fs_path_stack






events:
	- move into the next state
	- rivendell_fork
	- moria_fork
	- mordor_fork

**Comment by Helliaca** [comment]
START:
state 42 (Shire)

Road to Bree:
state 76 (old forest)
state 149 (Bree)

To Rivendell:
state 144 (South Downs)
state 64 (The Angle)
state 200 (Bruinen)
state 202 (Rivendell Ford)
state 65 (Rivendell)

**Comment by Helliaca** [comment]
DECISIONS



Launch covert interception attempt:
- Can only be done if prepared
- Only available on foreign territory
- Preparation requires X% intel netowrk
- cannot be done if helped fellowship
- Has a chance of lowering opinion of owner country


Launch interception attempt:
- Can be done if currentstate is owned
- Not preparing will still require you to quickly assign a leader
- No preparation necessary
- Costs a bunch of stuff
- cannot be done if helped fellowship


Help fellowship:
- Can be done if currentstate is owned
- Can only be done once per tag
- Cannot be done if tried to intercept



Prepare covert intercept:
- can be done on states in the pathstack
- Can be repeated up to 3x
- Requires at least X% intel network


Prepare an ambush:
- Can be done on any pathstack state that is owned
- Can be repeated up to 3x

**Comment by Helliaca** [comment]
FLAGS:
fs_started (global): Fellowship-event has started

VARS:
global.fs_currentstate: State the fellowship is currently in
global.fs_steps: How many states the fellowship has advanced in total

ARRAYS:
global.fs_path_stack: The states that the fellowship will move through in the future
global.fs_eventlog: Localizations of past events that have happened (use GetTokenLocalizedKey)
global.fs_eventlog_targets: Target scopes correspondings to each entry in the eventlog

**Comment by Helliaca** [comment]
RIV
- cant do anything

LTH
- can offer shelter or ignore
- when offered shelter:
	- dont
		- give gifts
		- have haldir escort them
		- both
		- nothing
	- try to take ring
		- frodo  agrees: ring is taken
		- frodo refuses: 
			- leave it be
			- escalate, try to take forcefully

MOR
- can only intercept
- several opportunities
- if ISE has gone good, can launch breakup-interception

ROH
- Can try to intercept
- Can help
- Eomer solo help?

GON
- Have boromir try to steal ring
- Faramir debacle in ithilien

ISE
- if gone evil:
	- can block path over moria
	- can launch interception in own territory
	- can launch breakup-interception in Emyn Muil


MOC
- can try to intercept

MIR
- if legolas can only help
- else can intercept

MOA
- if gimli can only help
- if no gimli can also intercept

ERE
- can try to intercept if no member was sent to rivendell
- otherwise can help



EVERYONE ELSE:
- can try to intercept
- can help

**Comment by Helliaca** [comment]
Some TODOs:

- [ ] Give Mordor decisions to corrupt the Ring-owning country
- [ ] Fix UI for when the Ring has been seized
- [ ] Fix UI for when the Ring has been destroyed
- [ ] Rohan focus tree

**Comment by Helliaca** [comment]
RIVENDELL:

- [ ] Give decision to gather support for fellowship
- [ ] Trigger event when fellowship arrives
- [ ] Event to decide whether if to send out Arwen?

**Comment by Helliaca** [comment]
NEWS EVENTS:

- [ ] Moria Battle
- [ ] Sarn-Gebir Battle
- [ ] Storm over the Misty Mountains

**Comment by Helliaca** [comment]
Country experiences:

- [ ] shire
- [ ] Cardolan
- [ ] Rhudaur
- [ ] Rivendell
- [ ] Enedwaith
- [ ] Angmar
- [ ] Vales
- [ ] Rohan
- [ ] Gondor
- [ ] Mordor
- [ ] Moria
- [ ] Orc-Moria
- [ ] Erebor
- [ ] Lothlorien
- [ ] Mirkwood

**Comment by Helliaca** [comment]
Tutorial:

- [ ] Adjust "War of the Ring" event (preferably uniquely per-country)
- [ ] Add a questionmark-button in details screen

**Comment by Helliaca** [comment]
BUGS:

- [ ] When you reload a save (at least sometimes) the map goes into the error-gollum

**Comment by Helliaca** [comment]
- [ ] Let the Council-of-Elrond members vote on which path the fellowship takes

**Comment by Helliaca** [comment]
- [ ] Fix isengard focus tree
- [ ] fix ring-catcher advisor
