### ISSUE TITLE
Small update

### ISSUE THREAD

**Issue by RubenVermaat** [Helliaca/HoI4-LotrMod#64]
- [x] Angmar -> Claim the North -> Not showing the names of any of the claims.
- [x] Rivendell -> Organized Licensing -> Not showing a desc nor what it adds
- [x] Moria -> Hunt down the Balrog! -> Making sure that Balrog is also removed as the leader of the fascist party
- [x] Generic tree -> unaligned_focus -> focus focus name and icon
- [x] Angmar -> Reworking political tree
       If Mordor goes "Resist Sauron" but Angmar goes Witch King, then Sauron can continue as the leader of Angmar as a really weird exile
- [x] Mordor -> proposes anti-elven pact -> mordor wargoal mirkwood, isengard wargoal imladris, angmar wargoal Lindon.
- [x] Dagorland -> can join a faction with the new focus tree.
- [x] Isengard -> Rallying the Tribes of dunland has a text error
- [x] Swords and spears have wrong texts on what they're exclusive with
- [x] ~~Fixing the Trickleback with negative losses~~ -> has been moved to own issue #67

**Comment by RubenVermaat** [comment]
- [ ] Rohans Focus "Prepare for War" adds "."
- [ ] The Rohan focus-effect for adaptable exports has a wrong idea name
- [ ] Text asking for confirmation to cancel railway building is wrong

**Comment by RubenVermaat** [comment]
- [ ] Gondors Focus "Faramir Doctrine" effect needs to be changed to something not Japan related

**Comment by RubenVermaat** [comment]
- [ ] Images when manually justifying the war are still the default ww2 images
- [ ] Isengard -> focus name warwithlorien should be fixed

**Comment by Helliaca** [comment]
- [ ] Arthedains Focus to conquer Arnor Adds empty claims

**Comment by RubenVermaat** [comment]
[ ] Fixing the shining focus icons not working

**Comment by RubenVermaat** [comment]
- [ ] Replaced question mark focus icons in Shire focus tree

**Comment by RubenVermaat** [comment]
- [ ] Fixing Dagorlad capital being wrong place

**Comment by RubenVermaat** [comment]
- [ ] Added two new focuses to the Monarchist path of Erebor

**Comment by RubenVermaat** [comment]
- [ ] Fix "Support Gonder revolution" focus text

**Comment by RubenVermaat** [comment]
- [ ] Fixed Erebor focus text "Prioritize Rare Minerals"
- [ ] Fixed location of Elven King's Halls
