### ISSUE TITLE
Angmar-Hotfix

### ISSUE THREAD

**Issue by RubenVermaat** [Helliaca/HoI4-LotrMod#76]
- [x] Fix the bug where all Nazgul are taken away when ambushing on Weathertop
- [x] Not killing Shelob as Mordor should also lower stability
- [x] Fix bug where non-alligned people can also accept war proposal against elven country
- [x] (Supposedly) Argonath raid can fail the stealth check, even though it should not
- [x] Correct localization errors mentioned in Discord #bug-report by @DancingBear
- [x] Fix "Industry Effort" not adding the factories to the correct states (Mordor)
- [x] Fix the request for trolls by Rhun not working correctly
- [x] Fix Rivendell Elven archer division starting weirdly (empty slot by column 2)
- [x] Correct title of focus "Expand the civilian" to "Expand the civilian industry" (Angmar)
- [x] Make sure the nazgulls get killed aswell when the ring is destroyed
- [x] "Demand Submission" should only be possible if Isengard still exists (Mordor)
- [x] Making sure AI (Angmar) goes belligerent by using the decisions
- [x] Fixing Gundabad small flags not showing correctly
- [x] Fix "Draw Closer to Mordor" depending on Gondor instead of Mordor (generic tree)
- [x] Fix manual justifying as Mordor being OP

**Comment by RubenVermaat** [comment]
Also reworking Military Effert path for Mordor. (including debuffing the start of Mordor a bit)

**Comment by Helliaca** [comment]
From #78 branch, I made the following, additional changes:
- Changed world tension icon
- Slowed down the fellowship's movement speed
